### ISSUE TITLE
如何改变颜色

### ISSUE THREAD

**Issue by Over-reaction** [pd4d10/vite-plugin-svgr#84]
使用这个 我如何改变svg的颜色

**Comment by JackpotM1103** [comment]
> 

参考 https://github.com/pd4d10/vite-plugin-svgr/issues/72#issue-1609038919 的方式引入 SVG 组件后，可通过 `<SvgIcon fill="currentColor" />`，以及 <svg> 下的 <path> 设置 `fill: inherit;` 来改变颜色

```js
<span style={{ color: "blue" }}>
  <SvgIcon
      className="change-color"
      fill="currentColor"
   />
</span>
```

```css
.change-color path{
  fill: inherit;
}
```

**Comment by chennlang** [comment]
可以在组件上加个 class, 然后通过 color 来控制颜色
```css
.custom-fill-svg {
  fill: currentColor;
  path, rect {
    fill: currentColor;
  }
}
```
```css
<Icon class="custom-fill-svg text-red-500" />
```
